config/routes.rb
Next::Application.routes.draw do

  resources :projects do
    resources :next_actions, shallow: true do 
      member do
        get 'cancel'
        get 'complete'
      end
    end
    member do
      get 'cancel'
      get 'complete'
    end
  end

  post "next_actions" => 'next_actions#create'

  get "pages/home"

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  root :to => 'next_actions#index'

  resources :users

end

app/controllers/next_actions_controller.rb
require 'chronic'
class NextActionsController < ApplicationController
  # GET /next_actions
  # GET /next_actions.json
  def index
    @next_actions = NextAction.where(state: 'current')
    @next_action = NextAction.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @next_actions }
    end
  end

  # GET /next_actions/1
  # GET /next_actions/1.json
  def show
    @next_action = NextAction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @next_action }
    end
  end

  # GET /next_actions/new
  # GET /next_actions/new.json
  def new
    @project = Project.find(params[:project_id])
    @next_action = @project.next_actions.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @next_action }
    end
  end

  # GET /next_actions/1/edit
  def edit
    @next_action = NextAction.find(params[:id])
  end

  # POST /next_actions
  # POST /next_actions.json
  def create
    @next_action = NextAction.new(params[:next_action])
    @next_action.due = Chronic.parse(params[:next_action][:due])

    if params[:project_id]
      @next_action.project_id = params[:project_id] 
    end

    respond_to do |format|
      if @next_action.save
        format.html { redirect_to @next_action.project, notice: 'Next action was successfully created.' }
        format.json { render json: @next_action, status: :created, location: @next_action }
      else
        format.html { render action: "new" }
        format.json { render json: @next_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /next_actions/1
  # PUT /next_actions/1.json
  def update
    @next_action = NextAction.find(params[:id])

    respond_to do |format|
      if @next_action.update_attributes(params[:next_action])
        format.html { redirect_to @next_action, notice: 'Next action was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @next_action.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /next_actions/1
  # DELETE /next_actions/1.json
  def destroy
    @next_action = NextAction.find(params[:id])
    @next_action.destroy

    respond_to do |format|
      format.html { redirect_to @next_action.project, notice: "#{@next_action.name} was deleted" }
      format.json { head :no_content }
    end
  end

  def cancel
    @next_action = NextAction.find(params[:id])
    @next_action.cancel

    respond_to do |format|
      format.html { redirect_to @next_action.project, notice: "#{@next_action.name} has be canceled."}
    end
  end

  def complete
    @next_action = NextAction.find(params[:id])
    @next_action.complete

    respond_to do |format|
      format.html { redirect_to @next_action.project, notice: "#{@next_action.name} has be completed."}
    end
  end
end

app/helpers/next_actions_helper.rb
module NextActionsHelper
end

app/views/next_actions/_form.html.haml
= form_for([@project, @next_action], html: {class: 'form-horizontal'}) do |f|
  - if @next_action.errors.any?
    #errorExplanation.alert-message.block-message.error
      %h2= "#{pluralize(@next_action.errors.count, 'error')} prohibited this next_action from being saved:"
      %ul
        - @next_action.errors.full_messages.each do |msg|
          %li= msg
 
  %fieldset
    %legend Action Description 
    .control-group
      = f.label :name, class: 'control-label'
      .controls
        = f.text_field :name
    .control-group
      = f.label :due, class: 'control-label'
      .controls
        = f.text_field :due
        = f.hidden_field :project_id
    .form-actions
      = f.submit 'Submit', class: 'btn btn-primary'

app/views/next_actions/edit.html.haml
%h1 Edit next_action
%p
  = link_to 'back', next_actions_path, class: 'btn'
  = link_to 'show', @next_action, class: 'btn primary'
= render 'form'

app/views/next_actions/index.html.haml
%h3 Next Actions
.well#add_next_action
  = form_for(@next_action, html: {class: 'form-inline'}) do |f|
    - if @next_action.errors.any?
      #errorExplanation.alert.alert-error
        %h2= "#{pluralize(@next_action.errors.count, 'error')} prohibited this next_action from being saved:"
        %ul
          - @next_action.errors.full_messages.each do |msg|
            %li= msg     
    = f.collection_select :project_id, Project.all, :id, :name
    = f.text_field :name, placeholder: 'Name'
    = f.text_field :due, placeholder: 'Due', class: 'input-small'
    = f.submit 'Submit', class: 'btn btn-primary'

%table.table.table-hover
  %thead
    %tr
      %th Project
      %th= NextAction.human_attribute_name :name
      %th= NextAction.human_attribute_name :due
      %th Actions
  
  %tbody
    - for next_action in @next_actions
      %tr{ :class => cycle(:odd, :even) }
        %td= link_to next_action.project.abbreviation, project_path(next_action.project), rel: 'tooltip', title: "#{next_action.project.name}"
        %td= next_action.name
        %td= next_action.due
        %td
          .btn-group
            = link_to 'Complete', complete_next_action_path(next_action), class: 'btn btn-small'
            %button.btn.dropdown-toggle{:'data-toggle'=> 'dropdown', class: 'btn-small'}
              .caret
            %ul.dropdown-menu
              %li= link_to "Cancel Action", cancel_next_action_path(next_action)
              %li= link_to "Delete Action", next_action, :method => 'delete', :data => {:confirm => 'Are you sure you want to delete this action?'}

app/views/next_actions/new.html.haml
%h1= "#{@project.name}"
= render 'form'

app/views/next_actions/show.html.haml
%h1 Show next_action
%p
  = link_to 'back', next_actions_path, class: 'btn'
  = link_to 'edit', edit_next_action_path(@next_action), class: 'btn primary'

%dl
  %dt= NextAction.human_attribute_name :name
  %dd= @next_action.name
  %dt= NextAction.human_attribute_name :due
  %dd= @next_action.due
  %dt= NextAction.human_attribute_name :sort
  %dd= @next_action.sort
  %dt= NextAction.human_attribute_name :state
  %dd= @next_action.state