config/routes.rb
Next::Application.routes.draw do

  resources :projects do
    resources :next_actions, shallow: true do 
      member do
        get 'cancel'
        get 'complete'
      end
    end
    member do
      get 'cancel'
      get 'complete'
    end
  end

  post "next_actions" => 'next_actions#create'

  get "pages/home"

  get "user_sessions/new"

  get "user_sessions/create"

  get "user_sessions/destroy"

  root :to => 'next_actions#index'

  resources :users

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :due, :name, :sort, :state, :abbreviation
  has_many :next_actions

  validates_presence_of :name, :abbreviation

  state_machine :state, :initial => :current do 
  	event :complete do
  		transition :current => :completed
  	end

  	event :cancel do
  		transition :current => :canceled
  	end
  end

  def current_next_actions
    next_actions.where(state: 'current')
  end
end

app/controllers/projects_controller.rb
require 'chronic'
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @next_action = NextAction.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.due = Chronic.parse(params[:project][:due])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for(@project, html: {class: 'form-horizontal'}) do |f|
  - if @project.errors.any?
    #errorExplanation.alert.alert-error
      %h2= "#{pluralize(@project.errors.count, 'error')} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg
 
  %fieldset
    %legend Project Information  
    .control-group
      = f.label :name, class: 'control-label'
      .controls
        = f.text_field :name
        %p.help-block The project name
    .control-group
      = f.label :abbreviation, class: 'control-label'
      .controls
        = f.text_field :abbreviation
    .control-group
      = f.label :due, class: 'control-label'
      .controls
        = f.text_field :due
        %p.help-block The date the project is due
    .form-actions
      = f.submit 'Submit', class: 'btn btn-primary'

app/views/projects/edit.html.haml
%h1 Edit project
%p
  = link_to 'back', projects_path, class: 'btn'
  = link_to 'show', @project, class: 'btn primary'
= render 'form'

app/views/projects/index.html.haml
%h1 Projects
%p= link_to 'New project', new_project_path, class: 'btn'

%table.table
  %thead
    %tr
      %th Name
      %th Due
      %th{style: 'text-align: center'} Next Actions
      %th{:colspan => 2} Actions
  
  %tbody
    - for project in @projects
      %tr{ :class => cycle(:odd, :even) }
        %td= link_to project.name, project
        %td= project.due
        %td{style: 'text-align: center'}= project.next_actions.count
        %td.action= link_to 'edit', edit_project_path(project)
        %td.action= link_to 'destroy', project, :confirm => 'Are you sure?', :method => :delete

app/views/projects/new.html.haml
%h1 New Project
= render 'form'

app/views/projects/show.html.haml
%h1#project_name= "Project: #{@project.name}"

#actions.btn-group
  = link_to 'Cancel Project', cancel_project_path(@project), class: 'btn'
  = link_to 'Complete Project', complete_project_path(@project), class: 'btn'

.well
  = form_for([@project, @next_action], html: {class: 'form-inline'}) do |f|
    - if @next_action.errors.any?
      #errorExplanation.alert.alert-error
        %h2= "#{pluralize(@next_action.errors.count, 'error')} prohibited this next_action from being saved:"
        %ul
          - @next_action.errors.full_messages.each do |msg|
            %li= msg     
    = f.text_field :name, placeholder: 'Name'
    = f.text_field :due, placeholder: 'Due', class: 'input-small'
    = f.hidden_field :project_id
    = f.submit 'Submit', class: 'btn btn-primary'


%h3 Next Actions
%table.table.table-borderd
  %tr
    %th Name
    %th Due
    %th Actions
    - @project.current_next_actions.each do |next_action|
      %tr
        %td= next_action.name
        %td= next_action.due
        %td
          .btn-group
            = link_to "Complete", complete_next_action_path(next_action), class: 'btn btn-small'
            %button.btn.dropdown-toggle{:'data-toggle'=> 'dropdown', class: 'btn-small'}
              .caret
            %ul.dropdown-menu
              %li= link_to "Cancel", cancel_next_action_path(next_action)
              %li= link_to "Delete", next_action, :method => 'delete', :data => {:confirm => 'Are you sure you want to delete this action?'}